-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, (A.PRICE * SUM(B.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS A
JOIN OFFLINE_SALE AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE ASC;

# SELECT p.PRODUCT_CODE, SUM(f.SALES_AMOUNT)*p.PRICE 'SALES'
# FROM PRODUCT p, OFFLINE_SALE f
# WHERE p.PRODUCT_ID = f.PRODUCT_ID
# GROUP BY p.PRODUCT_CODE
# ORDER BY SALES DESC, p.PRODUCT_CODE