-- 코드를 입력하세요
SELECT 
YEAR(B.SALES_DATE) AS YEAR, 
MONTH(B.SALES_DATE) AS MONTH, 
A.GENDER, 
COUNT( DISTINCT B.USER_ID) AS USERS
FROM USER_INFO AS A
JOIN ONLINE_SALE AS B
ON A.USER_ID = B.USER_ID AND A.GENDER IS NOT NULL
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER

# SELECT 
# YEAR(SALES_DATE) AS YEAR, 
# MONTH(SALES_DATE) AS MONTH, 
# USER_INFO.GENDER, 
# COUNT( DISTINCT ONLINE_SALE.USER_ID) AS USERS
# FROM ONLINE_SALE
# JOIN USER_INFO
# ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID AND
# GENDER IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER 
# ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER