-- 코드를 입력하세요
# SET @HOUR := -1;

# SELECT 
# (@HOUR := @HOUR +1) AS HOUR,
# (   SELECT COUNT(*) 
#     FROM ANIMAL_OUTS 
#     WHERE HOUR(DATETIME) = @HOUR
# ) AS COUNT 
# FROM ANIMAL_OUTS
# WHERE @HOUR < 23

# WITH RECURSIVE CTE AS(
#     SELECT 0 AS NUM
#     UNION ALL
#     SELECT NUM+1 
#     FROM CTE
#     WHERE NUM < 23
# )

# SELECT CTE.NUM AS HOUR, IFNULL(ANIMAL_OUTS.COUNT, 0) AS COUNT
# FROM CTE 
# LEFT JOIN (
#     SELECT HOUR(DATETIME) AS HOUR, 
#     COUNT(*) AS COUNT
#     FROM ANIMAL_OUTS
#     GROUP BY HOUR
# ) AS ANIMAL_OUTS 
# ON CTE.NUM = ANIMAL_OUTS.HOUR
# ORDER BY HOUR;

WITH RECURSIVE NUMBER_SEQ(HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 
    FROM NUMBER_SEQ 
    WHERE HOUR < 23
)

SELECT HOUR, 0 AS 'COUNT' 
FROM NUMBER_SEQ
WHERE HOUR NOT IN(
    SELECT CAST(date_format(DATETIME, '%H') AS signed) AS HOUR
    FROM ANIMAL_OUTS 
)
UNION
SELECT CAST(date_format(DATETIME, '%H') AS signed) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR
ORDER BY HOUR